- platform: workday
  country: BE

- platform: tod
  name: Night
  after: sunset
  after_offset: '-00:15:00'
  before: '07:00'

- platform: template
  sensors: 
    anyone_present_kitchen:
      friendly_name: "Is er iemand in de keuken"
      value_template: >-
        {% set result = namespace(value=false) %}
        {%- for entity_id in states.group.roomassistant_devices_all.attributes.entity_id -%}
          {%- if states(entity_id) == 'kitchen' %}
            {% set result.value = true %}
          {% endif -%}
        {%- endfor %}
        {{ result.value }}

- platform: template
  sensors: 
    anyone_present_living:
      friendly_name: "Is er iemand in de woonkamer"
      value_template: >-
        {% set result = namespace(value=false) %}
        {%- for entity_id in states.group.roomassistant_devices_all.attributes.entity_id -%}
          {%- if states(entity_id) == 'living' %}
            {% set result.value = true %}
          {% endif -%}
        {%- endfor %}
        {{ result.value }}

- platform: template
  sensors: 
    anyone_present_bedroom:
      friendly_name: "Is er iemand in de slaapkamer"
      value_template: >-
        {% set result = namespace(value=false) %}
        {%- for entity_id in states.group.roomassistant_devices_all.attributes.entity_id -%}
          {%- if states(entity_id) == 'bedroom' %}
            {% set result.value = true %}
          {% endif -%}
        {%- endfor %}
        {{ result.value }}

- platform: template
  sensors: 
    anyone_present_bathroom:
      friendly_name: "Is er iemand in de badkamer"
      value_template: >-
        {% set result = namespace(value=false) %}
        {%- for entity_id in states.group.roomassistant_devices_all.attributes.entity_id -%}
          {%- if states(entity_id) == 'bathroom' %}
            {% set result.value = true %}
          {% endif -%}
        {%- endfor %}
        {{ result.value }}

- platform: template
  sensors: 
    anyone_present_office:
      friendly_name: "Is er iemand in de bureau"
      value_template: >-
        {% set result = namespace(value=false) %}
        {%- for entity_id in states.group.roomassistant_devices_all.attributes.entity_id -%}
          {%- if states(entity_id) == 'office' %}
            {% set result.value = true %}
          {% endif -%}
        {%- endfor %}
        {{ result.value }}