- platform: generic
  still_image_url: !secret camera_url_entry_still
  stream_source: !secret camera_url_entry_stream
  name: entry

- platform: generic
  still_image_url: !secret camera_url_garden_still
  stream_source: !secret camera_url_garden_stream
  name: garden
