default_config:
frontend: !include frontend.yaml
recorder: !include recorder.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml
light: !include lights.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
tts: !include tts.yaml
ios: !include ios.yaml
notify: !include notify.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
webostv: !include webostvs.yaml
utility_meter: !include utility_meters.yaml