default_config:
frontend: !include frontend.yaml
recorder: !include recorder.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml
light: !include lights.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
vacuum: !include vacuums.yaml
binary_sensor: !include binary_sensors.yaml
tts: !include tts.yaml
asuswrt: !include asuswrt.yaml
homekit: !include homekit.yaml
camera: !include cameras.yaml