- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: uptime

- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

- platform: template
  sensors:
    living_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.living', 'temperature') }}"
    
    kitchen_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.kitchen', 'temperature') }}"

    bathroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.bathroom', 'temperature') }}"

    bedroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.bedroom', 'temperature') }}"

    storage_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.storage', 'temperature') }}"

    office_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.office', 'temperature') }}"

    guestroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.guestroom', 'temperature') }}"

    alarm:
      friendly_name: "Wekker vandaag"
      value_template: >-
        {% if is_state('input_boolean.vacation', 'on') or is_state('binary_sensor.workday_sensor', 'off')  %}
          {{ states('input_datetime.alarm_dayoff') }}
        {%- else -%}
          {{ states('input_datetime.alarm_workday') }}
        {% endif %}

    bedtime:
      friendly_name: "Bedtijd vandaag"
      value_template: >-
        {% if is_state('input_boolean.vacation', 'on') or is_state('binary_sensor.workday_sensor', 'off')  %}
          {{ states('input_datetime.bedtime_dayoff') }}
        {%- else -%}
          {{ states('input_datetime.bedtime_workday') }}
        {% endif %}

    day_phase:
      friendly_name: "Fase van de dag"
      value_template: >-
        {% if states.group.persons_all.state == "not_home" %}
          Away
        {% elif states.input_boolean.do_not_disturb.state == "on" %}
          Sleeping
        {% elif states.input_boolean.vacation.state == "on" or states.binary_sensor.workday_sensor.state == "off" %}
          {% if states.sensor.time.state < states.sensor.bedtime.state %}
            Leisure
          {% else %}
            Bedtime
          {% endif %}
        {% else %}
          {% if states.sensor.time.state < states.input_datetime.workday_start.state %}
            Waking
          {% elif states.sensor.time.state >= states.input_datetime.workday_start.state and states.sensor.time.state < states.input_datetime.workday_stop.state %}
            Working
          {% elif states.sensor.time.state >= states.input_datetime.workday_stop.state and states.sensor.time.state < states.sensor.bedtime.state %}
            Leisure
          {% else %}
            Bedtime
          {% endif %}
        {% endif %}

    vacuum_battery_level:
      value_template: "{{ state_attr('vacuum.portia', 'battery_level') }}"
      device_class: battery
      unit_of_measurement: '%'

    vacuum_main_brush_left:
      value_template: "{{ state_attr('vacuum.portia', 'main_brush_left') }}"
      unit_of_measurement: 'uren'
    
    vacuum_side_brush_left:
      value_template: "{{ state_attr('vacuum.portia', 'side_brush_left') }}"
      unit_of_measurement: 'uren'

    vacuum_filter_left:
      value_template: "{{ state_attr('vacuum.portia', 'filter_left') }}"
      unit_of_measurement: 'uren'
    
    vacuum_sensor_dirty_left:
      value_template: "{{ state_attr('vacuum.portia', 'sensor_dirty_left') }}"
      unit_of_measurement: 'uren'

    vacuum_mop_attached:
      value_template: "{{ state_attr('vacuum.portia', 'mop_attached') }}"

    daily_energy:
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.daily_energy_offpeak')|float + states('sensor.daily_energy_peak')|float }}"

    monthly_energy:
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.monthly_energy_offpeak')|float + states('sensor.monthly_energy_peak')|float }}"