- platform: template
  sensors:
    living_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.living', 'temperature') }}"
    
    kitchen_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.kitchen', 'temperature') }}"

    bathroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.bathroom', 'temperature') }}"

    bedroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.bedroom', 'temperature') }}"

    storage_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.storage', 'temperature') }}"

    office_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.office', 'temperature') }}"

    guestroom_set_temperature:
      unit_of_measurement: '°'
      value_template: "{{ state_attr('climate.guestroom', 'temperature') }}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'