- platform: template
  switches:
    heating_living:
      friendly_name: "Woonkamer"
      value_template: "{{ (states('sensor.living_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.woonkamer
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.woonkamer

    heating_kitchen:
      friendly_name: "Keuken"
      value_template: "{{ (states('sensor.kitchen_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.keuken
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.keuken

    heating_bathroom:
      friendly_name: "Badkamer"
      value_template: "{{ (states('sensor.bathroom_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.badkamer
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.badkamer

    heating_bedroom:
      friendly_name: "Slaapkamer"
      value_template: "{{ (states('sensor.bedroom_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.slaapkamer
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.slaapkamer

    heating_office:
      friendly_name: "Kantoor"
      value_template: "{{ (states('sensor.office_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.kantoor
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.kantoor

    heating_guestroom:
      friendly_name: "Gastkamer"
      value_template: "{{ (states('sensor.guestroom_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.gastenkamer
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.gastenkamer

    heating_storage:
      friendly_name: "Berging"
      value_template: "{{ (states('sensor.guestroom_set_temperature') | float) > (states('input_number.heating_standby') | float) }}"
      turn_on:
        service: script.turn_on_heating
        data:
          climate: climate.berging
      turn_off:
        service: script.turn_off_heating
        data:
          climate: climate.berging

    litterbox_needs_cleaning:
      friendly_name: "Kattenbak is vuil"
      value_template: "{{ (states('input_number.litterbox_visits') | int) > (states('input_number.litterbox_visits_max') | int) }}"
      turn_on:
        service: script.notify_mobile
        data:
          title: "Kattenbak"
          message: "🐈 De kattenbak is vuil"
          sound: "meow.wav"
      turn_off:
        service: input_number.set_value
        data:
          entity_id: input_number.litterbox_visits
          value: 0