- alias: Motion in Bathroom During the Day
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.bathroom_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: input_boolean.bathroom_motion_on
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.bathroom_bright

- alias: Motion in Bathroom at Night
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.bathroom_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'on'
  - condition: state
    entity_id: input_boolean.bathroom_motion_on
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.bathroom_dim
    
- alias: No More Motion in Bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_bathroom')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.bathroom_motion_on
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bathroom