- alias: Motion in Entry
  trigger:
  - platform: state
    entity_id: binary_sensor.entry_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.entry_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.entry_bright

- alias: No More Motion in Entry in the Evening
  trigger:
  - platform: state
    entity_id: binary_sensor.entry_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_hallways')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: scene.turn_on
    entity_id: scene.entry_dim

- alias: No More Motion in Entry During the Day
  trigger:
  - platform: state
    entity_id: binary_sensor.entry_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_hallways')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: 'above_horizon'
  action:
  - service: light.turn_off
    entity_id: light.entry
    
- alias: Turn Entry Light Off
  trigger:
    platform: time
    at: "23:00:00"
  action:
  - service: light.turn_off
    entity_id: light.entry