- alias: Motion in Kitchen
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.kitchen_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: input_boolean.kitchen_motion_on
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.kitchen_bright

- alias: No More Motion in Kitchen in the Evening
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_kitchen')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: binary_sensor.night
    state: 'on'
  - condition: state
    entity_id: input_boolean.kitchen_motion_on
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.kitchen_dim
    
- alias: No More Motion in Kitchen During the Day
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_kitchen')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: state
    entity_id: binary_sensor.night
    state: 'off'
  - condition: state
    entity_id: input_boolean.kitchen_motion_on
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.kitchen