- alias: Motion in Stairs
  trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.stairs_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.stairs_bright

- alias: Motion in Stairs around Bedtime
  trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.stairs_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  - condition: time
    after: '21:00:00'
    before: '04:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.bedroom_nightstands_bright
    
- alias: No More Motion in Stairs
  trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_hallways')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.stairs