- alias: Motion in Storage Room
  trigger:
  - platform: state
    entity_id: binary_sensor.storage_motion
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (states('sensor.storage_motion') | float) < (states('input_number.lux_treshold') | float) }}"
  action:
  - service: scene.turn_on
    entity_id: scene.storage_bright
    
- alias: No More Motion in Storage Room
  trigger:
  - platform: state
    entity_id: binary_sensor.storage_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_storage')|int }}"
  action:
  - service: light.turn_off
    entity_id: light.storage