- alias: Motion in Toilet
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.toilet_bright
    
- alias: No More Motion in Toilet
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.light_timeout_toilet')|int }}"
  action:
  - service: light.turn_off
    entity_id: light.toilet