- alias: Toggle Fan
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_niko
      event: 1000
  action:
    - service: switch.toggle
      entity_id: switch.bathroom_fan
      
- alias: Turn On Bath Mode
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_niko
      event: 2000
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bathroom_motion_on
    - service: light.turn_on
      entity_id: light.bathroom
      data_template:
        hs_color:
          - "{{ range(360)|random }}"
          - "{{ range(80,101)|random }}"
        brightness_pct: 100

- alias: Turn On Bathroom Light
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_niko
      event: 3000
  action:
    - service: scene.turn_on
      entity_id: scene.bathroom_bright
    - service: input_boolean.turn_on
      entity_id: input_boolean.bathroom_motion_on
    
- alias: Turn Off Bathroom Light
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_niko
      event: 4000
  action:
    - service: light.turn_off
      entity_id: light.bathroom
    - service: input_boolean.turn_on
      entity_id: input_boolean.bathroom_motion_on