- alias: Turn On Bedroom Nightstands
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 1000
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_nightstands_bright
    
- alias: Turn Off Bedroom Nightstands
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 2000
  action:
    - service: light.turn_off
      entity_id: light.bedroom
    
- alias: Turn On Bedroom Spot
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 3000
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_bright
    
- alias: Turn Off Bedroom Spot
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 4000
  action:
    - service: light.turn_off
      entity_id: light.bedroom

- alias: Start the night but light in the bedroom
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 5000
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.do_not_disturb
    - delay: '00:00:01'
    - service: scene.turn_on
      entity_id: scene.bedroom_nightstands_bright

- alias: Start the night
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_niko
      event: 6000
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.do_not_disturb