- alias: Do Not Disturbed Enabled
  trigger:
  - platform: state
    entity_id: input_boolean.do_not_disturb
    to: 'on'
  condition:
  - condition: state
    entity_id: group.persons_all
    state: 'home'
  action:
  - service: script.turn_on
    entity_id: script.reset_lights

- alias: Disable Do Not Disturb
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == strptime(states.sensor.alarm.state, '%H:%M:%S').strftime('%H:%M') }}"
  condition:
  - condition: state
    entity_id: input_boolean.do_not_disturb
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.do_not_disturb