- alias: Motion in Mailbox
  trigger:
  - platform: state
    entity_id: binary_sensor.entry_mailbox
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.mailbox_mail
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.mailbox_mail

- alias: There is mail
  trigger:
  - platform: state
    entity_id: input_boolean.mailbox_mail
    to: 'on'
  action:
  - service: input_number.increment
    entity_id: input_number.badge_count
  - service: script.notify_mobile
    data:
      title: "Brievenbus"
      message: "📬 Er is post"
      sound: "new-mail.caf"

- alias: Mail has been collected
  trigger:
  - platform: state
    entity_id: input_boolean.mailbox_mail
    to: 'off'
  action:
  - service: input_number.decrement
    entity_id: input_number.badge_count