- alias: Update notification badge
  trigger:
  - platform: state
    entity_id: input_number.badge_count
  action:
  - service: notify.mobile_app_yannicks_iphone
    data_template:
      message: "delete_alert"
      data:
        push:
          badge: "{{ (states('input_number.badge_count') | int) }}"