- alias: Noone is Home
  trigger:
  - platform: state
    entity_id: group.persons_all
    to: "not_home"
  action:
  - service: light.turn_off
    entity_id: light.bedroom
  - service: light.turn_off
    entity_id: light.office