- alias: Light Theme After Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: frontend.set_theme
      data:
        name: Google Light Theme

- alias: Dark Theme After Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: frontend.set_theme
      data:
        name: Google Dark Theme

- alias: Light Theme After Reboot in Day
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    service: frontend.set_theme
    data:
      name: Google Light Theme

- alias: Dark Theme After Reboot in Night
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: frontend.set_theme
    data:
      name: Google Dark Theme
      